[package]
name = "server"
edition = "2021"

[dependencies]
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
workspace_hack = { version = "0.1", path = "../workspace_hack" }
